name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check current directory
        run: pwd  # Выведет текущую рабочую директорию

      - name: Show go.mod content
        run: cat go.mod  # Покажет содержимое go.mod для диагностики

      - name: Clean Go cache
        run: go clean -modcache  # Очистка кеша зависимостей

      - name: Download dependencies
        run: go mod tidy  # Загружаем зависимости

      - name: Run tests
        run: go test -v ./...  # Запуск тестов

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/42-docker-final:${{ github.ref_name }}
